
waypoints:
  - id: 1
    name: main_corridor_start
    type: passage
    x: 0.70
    y: 1.00
    yaw: 0.0
    check_items:
      - obstacle

  - id: 2
    name: restricted_room_A
    type: restricted_area
    x: 1.25
    y: -1.85
    yaw: 1.57
    check_items:
      - person

  - id: 3
    name: central_corridor_obstacle_zone
    type: passage
    x: 2.70
    y: -0.75
    yaw: 0.0
    check_items:
      - obstacle

  - id: 4
    name: upper_back_corridor
    type: passage
    x: 4.20
    y: 1.20
    yaw: 3.14
    check_items:
      - obstacle

  - id: 5
    name: lab_entrance_restricted
    type: restricted_area
    x: 1.65
    y: 1.35
    yaw: 3.14
    check_items:
      - person

# waypoints:
#   - id: 1
#     name: main_corridor_start
#     type: passage
#     x: 0.30
#     y: 0.25
#     yaw: 0.0
#     check_items:
#       - obstacle

#   - id: 2
#     name: restricted_room_A
#     type: restricted_area
#     x: 1.10
#     y: -1.35
#     yaw: 1.57
#     check_items:
#       - person

#   - id: 3
#     name: far_corridor_obstacle_zone
#     type: passage
#     x: 3.10
#     y: 0.55
#     yaw: 0.0
#     check_items:
#       - obstacle

#   - id: 4
#     name: upper_back_corridor
#     type: passage
#     x: 1.70
#     y: 1.45
#     yaw: 3.14
#     check_items:
#       - obstacle

#   - id: 5
#     name: lab_entrance_restricted
#     type: restricted_area
#     x: 3.85
#     y: 1.35
#     yaw: 1.57
#     check_items:
#       - person